### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ciconia** [svenax/bagpipemusic#4]
Please add a software license so that I can fork this repository. I'd like to turn the bagpipe music functionality into a [lyp](https://github.com/noteflakes/lyp) package.

**Comment by svenax** [comment]
Please explain in more detail what you'd like to make into a package. You are aware that `bagpipe.ly`, which is the same as my `bagpipe_new.ly`, is included in the standard Lilypond distribution, right?

**Comment by ciconia** [comment]
Wasn't aware of that. In that case there's no point in continuing. Thanks all the same.
